# Generated by Django 6.0.2 on 2026-02-05 17:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KnownAsset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45, unique=True)),
                ('device_type', models.CharField(max_length=50)),
                ('trust_level', models.CharField(default='Medium', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('trained_on', models.DateField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('traffic_id', models.AutoField(primary_key=True, serialize=False)),
                ('src_ip', models.CharField(max_length=15)),
                ('dst_ip', models.CharField(max_length=15)),
                ('protocol', models.CharField(max_length=10)),
                ('packet_count', models.IntegerField()),
                ('byte_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Analyst', 'Analyst')], default='Analyst', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='traffic_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='traffic_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackLog',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.IntegerField()),
                ('feedback_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_monitor.alert')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='traffic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_monitor.networktraffic'),
        ),
    ]
