# Generated by Django 6.0.2 on 2026-03-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0002_mlmodel_f1_score_mlmodel_file_path_mlmodel_precision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('primary', 'Primary Analyst'), ('secondary', 'Secondary Analyst')], default='secondary', max_length=20),
        ),
    ]
