# Generated by Django 6.0.2 on 2026-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0003_alter_alert_severity_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='networktraffic',
            name='flow_features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
